"""esquema base

Revision ID: f3f4bed7765b
Revises: 
Create Date: 2026-10-01 16:35:15.123856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3f4bed7765b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=150), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cost_mxn', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('api_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_costs_action'), 'api_costs', ['action'], unique=False)
    op.create_index(op.f('ix_api_costs_created_at'), 'api_costs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_costs_service'), 'api_costs', ['service'], unique=False)
    op.create_index(op.f('ix_api_costs_unit'), 'api_costs', ['unit'], unique=False)
    op.create_table('chatbot_config',
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('phone_number_id', sa.String(length=80), nullable=True),
    sa.Column('wa_business_account_id', sa.String(length=80), nullable=True),
    sa.Column('wa_access_token', sa.Text(), nullable=True),
    sa.Column('webhook_verify_token', sa.String(length=120), nullable=True),
    sa.Column('closer_user_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('unit')
    )
    op.create_index(op.f('ix_chatbot_config_webhook_verify_token'), 'chatbot_config', ['webhook_verify_token'], unique=False)
    op.create_table('chatbot_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wa_phone', sa.String(length=30), nullable=False),
    sa.Column('wa_name', sa.String(length=150), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('lead_data', sa.JSON(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_conversations_status'), 'chatbot_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_chatbot_conversations_unit'), 'chatbot_conversations', ['unit'], unique=False)
    op.create_index(op.f('ix_chatbot_conversations_wa_phone'), 'chatbot_conversations', ['wa_phone'], unique=False)
    op.create_table('comision_descuentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descuento_desde', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('factor', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('etiqueta', sa.String(length=120), nullable=True),
    sa.Column('requiere_autorizacion', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comision_etapas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('peso', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('comision_politica',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meta_habilita_pago', sa.Boolean(), nullable=False),
    sa.Column('umbral', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('base', sa.String(length=20), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comision_tasas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unidad', sa.String(length=40), nullable=False),
    sa.Column('monto_desde', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_hasta', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tasa', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('modalidad', sa.String(length=60), nullable=True),
    sa.Column('es_multi_un', sa.Boolean(), nullable=False),
    sa.Column('regla_origen', sa.Text(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comision_tasas_unidad'), 'comision_tasas', ['unidad'], unique=False)
    op.create_table('customer_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_name', sa.String(length=255), nullable=True),
    sa.Column('zoho_account_id', sa.String(length=64), nullable=True),
    sa.Column('savio_customer_ids', sa.Text(), nullable=True),
    sa.Column('cs_account_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos_publicidad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plataforma', sa.Enum('Facebook', 'Instagram', 'Google', 'TikTok', 'Otro', name='plataforma_ads_enum'), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('campana', sa.String(length=200), nullable=True),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_campaigns',
    sa.Column('campaign_id', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=False),
    sa.Column('unidad', sa.String(length=60), nullable=False),
    sa.Column('estado_default', sa.String(length=80), nullable=True),
    sa.Column('zonas', postgresql.ARRAY(sa.String(length=80)), server_default='{}', nullable=False),
    sa.Column('activa', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('proyecto_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('autor', sa.String(length=150), nullable=False),
    sa.Column('prioridad', sa.String(length=50), nullable=True),
    sa.Column('votos', sa.Integer(), nullable=False),
    sa.Column('prompt_dev', sa.Text(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('fase_num', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savio_customers',
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('current_state', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_savio_customers_tax_id'), 'savio_customers', ['tax_id'], unique=False)
    op.create_table('savio_invoices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('uen', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('sum_mrr', sa.Boolean(), nullable=False),
    sa.Column('sub', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savio_invoices_customer_id'), 'savio_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_savio_invoices_date'), 'savio_invoices', ['date'], unique=False)
    op.create_index(op.f('ix_savio_invoices_unit'), 'savio_invoices', ['unit'], unique=False)
    op.create_table('savio_payments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('method', sa.String(length=60), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savio_payments_customer_id'), 'savio_payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_savio_payments_date'), 'savio_payments', ['date'], unique=False)
    op.create_index(op.f('ix_savio_payments_invoice_id'), 'savio_payments', ['invoice_id'], unique=False)
    op.create_table('savio_subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mrr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('uen', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('sum_mrr', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savio_subscriptions_customer_id'), 'savio_subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_savio_subscriptions_unit'), 'savio_subscriptions', ['unit'], unique=False)
    op.create_table('savio_sync_state',
    sa.Column('resource', sa.String(length=40), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('resource')
    )
    op.create_table('scip_director_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=120), nullable=False),
    sa.Column('campaign_name', sa.Text(), nullable=False),
    sa.Column('campaign_platform', sa.String(length=40), nullable=True),
    sa.Column('campaign_unit', sa.String(length=40), nullable=True),
    sa.Column('director_user_id', sa.UUID(), nullable=False),
    sa.Column('director_name', sa.String(length=150), nullable=False),
    sa.Column('decided_action', sa.String(length=80), nullable=False),
    sa.Column('scale_to_campaign_id', sa.String(length=120), nullable=True),
    sa.Column('scale_to_campaign_name', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('data_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('options_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('executed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('executed_by_name', sa.String(length=150), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketing_notes', sa.Text(), nullable=True),
    sa.Column('ad_id', sa.String(length=120), nullable=True),
    sa.Column('ad_name', sa.Text(), nullable=True),
    sa.Column('seller_user_id', sa.UUID(), nullable=True),
    sa.Column('seller_name', sa.String(length=150), nullable=True),
    sa.Column('scale_to_seller_id', sa.UUID(), nullable=True),
    sa.Column('scale_to_seller_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scip_director_recommendations_campaign_id'), 'scip_director_recommendations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_scip_director_recommendations_created_at'), 'scip_director_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_scip_director_recommendations_status'), 'scip_director_recommendations', ['status'], unique=False)
    op.create_table('sdr_dir_credits_monthly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('service', sa.String(length=40), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('credits_limit', sa.Integer(), nullable=False),
    sa.Column('hard_cap', sa.Boolean(), nullable=False),
    sa.Column('alert_threshold', sa.Float(), nullable=False),
    sa.Column('alerted_80', sa.Boolean(), nullable=False),
    sa.Column('alerted_95', sa.Boolean(), nullable=False),
    sa.Column('alerted_100', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit', 'service', 'year_month', name='uq_sdr_credits_unit_service_month')
    )
    op.create_index('idx_sdr_credits_unit_service_month', 'sdr_dir_credits_monthly', ['unit', 'service', 'year_month'], unique=False)
    op.create_table('sdr_dir_engine_config',
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_companies_per_day', sa.Integer(), nullable=False),
    sa.Column('max_contacts_per_company', sa.Integer(), nullable=False),
    sa.Column('max_lusha_credits_per_day', sa.Integer(), nullable=False),
    sa.Column('min_lusha_balance_alert', sa.Integer(), nullable=False),
    sa.Column('lemlist_master_campaign_id', sa.Text(), nullable=True),
    sa.Column('cron_hour', sa.Integer(), nullable=False),
    sa.Column('cron_minute', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_summary', sa.Text(), nullable=True),
    sa.Column('tam_a_enrich_phone', sa.Boolean(), nullable=False),
    sa.Column('tam_bc_enrich_phone', sa.Boolean(), nullable=False),
    sa.Column('tam_a_phones_per_company', sa.Integer(), nullable=False),
    sa.Column('tam_bc_phones_per_company', sa.Integer(), nullable=False),
    sa.Column('lusha_monthly_limit', sa.Integer(), nullable=False),
    sa.Column('lusha_hard_cap', sa.Boolean(), nullable=False),
    sa.Column('lusha_alert_threshold', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('unit')
    )
    op.create_table('sdr_dir_engine_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('companies_attempted', sa.Integer(), nullable=False),
    sa.Column('companies_processed', sa.Integer(), nullable=False),
    sa.Column('companies_no_contacts', sa.Integer(), nullable=False),
    sa.Column('contacts_pushed_to_lemlist', sa.Integer(), nullable=False),
    sa.Column('lusha_credits_used', sa.Integer(), nullable=False),
    sa.Column('apollo_calls', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdr_dir_engine_runs_unit'), 'sdr_dir_engine_runs', ['unit'], unique=False)
    op.create_table('sdr_dir_master_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('apollo_query', sa.Text(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('tam', sa.String(length=10), nullable=True),
    sa.Column('origen', sa.String(length=60), nullable=True),
    sa.Column('sucursales', sa.Integer(), nullable=True),
    sa.Column('estados', sa.Text(), nullable=True),
    sa.Column('seniorities', sa.Text(), nullable=True),
    sa.Column('departments', sa.Text(), nullable=True),
    sa.Column('priority_titles', sa.Text(), nullable=True),
    sa.Column('requires_manual', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('contacts_found', sa.Integer(), nullable=False),
    sa.Column('lusha_credits_used', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('apollo_alt_queries', sa.Text(), nullable=True),
    sa.Column('apollo_industry', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('exclude_keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sdr_master_status_priority', 'sdr_dir_master_companies', ['status', 'priority_order'], unique=False)
    op.create_index('idx_sdr_master_unit_status', 'sdr_dir_master_companies', ['unit', 'status'], unique=False)
    op.create_index(op.f('ix_sdr_dir_master_companies_status'), 'sdr_dir_master_companies', ['status'], unique=False)
    op.create_index(op.f('ix_sdr_dir_master_companies_unit'), 'sdr_dir_master_companies', ['unit'], unique=False)
    op.create_table('sdr_dir_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('company_domain', sa.Text(), nullable=True),
    sa.Column('company_industry', sa.Text(), nullable=True),
    sa.Column('company_size', sa.String(length=40), nullable=True),
    sa.Column('company_country', sa.String(length=40), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('suggested_to', sa.Integer(), nullable=True),
    sa.Column('suggested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdr_dir_suggestions_status'), 'sdr_dir_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_sdr_dir_suggestions_suggested_to'), 'sdr_dir_suggestions', ['suggested_to'], unique=False)
    op.create_index(op.f('ix_sdr_dir_suggestions_unit'), 'sdr_dir_suggestions', ['unit'], unique=False)
    op.create_table('sdr_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('instagram_handle', sa.Text(), nullable=True),
    sa.Column('whatsapp', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('branches', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_ad_url', sa.Text(), nullable=True),
    sa.Column('facebook_url', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('maps_url', sa.Text(), nullable=True),
    sa.Column('wa_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdr_results_assigned_to'), 'sdr_results', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_sdr_results_status'), 'sdr_results', ['status'], unique=False)
    op.create_index(op.f('ix_sdr_results_unit'), 'sdr_results', ['unit'], unique=False)
    op.create_table('users_crm',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.Enum('Developer', 'Super Admin', 'Super Admin Aromatex', 'Super Admin Pestex', 'Super Admin Comercial', 'Super Admin Nexo', 'Gerente Comercial Aromatex', 'Revisión Comercial', 'Vendedor', 'KAM', name='rol_crm_enum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono_whatsapp', sa.String(length=30), nullable=True),
    sa.Column('rol_comercial', sa.Enum('Gerente de Ventas', 'Líder Comercial', 'Asesor Comercial', 'SDR', name='rol_comercial_enum'), nullable=False),
    sa.Column('especialidad_marca', postgresql.ARRAY(sa.String(length=80)), server_default='{}', nullable=False),
    sa.Column('ultimo_lead_asignado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('en_turno', sa.Boolean(), nullable=False),
    sa.Column('perfil_multi_un', sa.Boolean(), nullable=False),
    sa.Column('baileys_session', sa.String(length=50), nullable=True),
    sa.Column('zona_cobertura', postgresql.ARRAY(sa.String(length=80)), server_default='{}', nullable=False),
    sa.Column('gmail_address', sa.String(length=200), nullable=True),
    sa.Column('email_signature', sa.Text(), nullable=True),
    sa.Column('gmail_backfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmail_backfilled_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correos_visibles_para_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['correos_visibles_para_user_id'], ['users_crm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # users_crm y usuarios se apuntan mutuamente, asi que no hay ningun orden
    # en el que se puedan crear las dos con sus FK en linea. La de users_crm
    # se agrega aqui, con ALTER, cuando ya existen ambas tablas.
    #
    # El autogenerate no resuelve esto solo: avisa "unresolvable cycles between
    # tables users_crm, usuarios" y emite un orden que falla. Si algun dia se
    # regenera este baseline, hay que volver a mover esta linea.
    op.create_foreign_key('users_crm_usuario_id_fkey', 'users_crm', 'usuarios',
                          ['usuario_id'], ['id'])
    op.create_table('zoho_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=255), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('industria', sa.String(length=120), nullable=True),
    sa.Column('tamano', sa.String(length=60), nullable=True),
    sa.Column('num_sucursales', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=120), nullable=True),
    sa.Column('pais', sa.String(length=60), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('is_cliente', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('cs_account_id', sa.UUID(), nullable=True),
    sa.Column('zoho_account_id', sa.String(length=80), nullable=True),
    sa.Column('customer_master_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zoho_account_id')
    )
    op.create_index(op.f('ix_accounts_client_id'), 'accounts', ['client_id'], unique=True)
    op.create_index(op.f('ix_accounts_cs_account_id'), 'accounts', ['cs_account_id'], unique=False)
    op.create_index(op.f('ix_accounts_customer_master_id'), 'accounts', ['customer_master_id'], unique=False)
    op.create_index(op.f('ix_accounts_estado'), 'accounts', ['estado'], unique=False)
    op.create_index(op.f('ix_accounts_nombre'), 'accounts', ['nombre'], unique=True)
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_accounts_rfc'), 'accounts', ['rfc'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('permisos', sa.JSON(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=True),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usos', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['users_crm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('chatbot_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatbot_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_messages_conversation_id'), 'chatbot_messages', ['conversation_id'], unique=False)
    op.create_table('city_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('round_robin_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_assignments_city'), 'city_assignments', ['city'], unique=False)
    op.create_index(op.f('ix_city_assignments_unit'), 'city_assignments', ['unit'], unique=False)
    op.create_index(op.f('ix_city_assignments_user_id'), 'city_assignments', ['user_id'], unique=False)
    op.create_table('comision_cortes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('meta_mxn', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vendido_mxn', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cumplimiento', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('comision_mxn', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('decidido_por', sa.String(length=120), nullable=True),
    sa.Column('decidido_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'mes', name='uq_corte_usuario_mes')
    )
    op.create_index(op.f('ix_comision_cortes_mes'), 'comision_cortes', ['mes'], unique=False)
    op.create_index(op.f('ix_comision_cortes_usuario_id'), 'comision_cortes', ['usuario_id'], unique=False)
    op.create_table('cs_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('kam_id', sa.UUID(), nullable=True),
    sa.Column('es_cuenta_nueva', sa.Boolean(), nullable=True),
    sa.Column('en_due_diligence', sa.Boolean(), nullable=True),
    sa.Column('origen_adquisicion', sa.String(length=80), nullable=True),
    sa.Column('dd_metadata', sa.JSON(), nullable=True),
    sa.Column('mrr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mrr_observado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('arr_proyectado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sucursales', sa.Integer(), nullable=True),
    sa.Column('unidades_contratadas', sa.String(length=100), nullable=True),
    sa.Column('facturacion_q1', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pagado_q1', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pendiente_q1', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('num_facturas_q1', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('survey_token', sa.String(length=32), nullable=True),
    sa.Column('ticket_token', sa.String(length=32), nullable=True),
    sa.Column('giro', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('adjuntos', sa.JSON(), nullable=True),
    sa.Column('nps', sa.Float(), nullable=True),
    sa.Column('pulso', sa.String(length=20), nullable=True),
    sa.Column('eficiencia_operativa', sa.Float(), nullable=True),
    sa.Column('fecha_renovacion', sa.Date(), nullable=True),
    sa.Column('valor_contrato', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ejecutivo_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ejecutivo_id'], ['users_crm.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kam_id'], ['users_crm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cs_accounts_ejecutivo_id'), 'cs_accounts', ['ejecutivo_id'], unique=False)
    op.create_index(op.f('ix_cs_accounts_en_due_diligence'), 'cs_accounts', ['en_due_diligence'], unique=False)
    op.create_index(op.f('ix_cs_accounts_fecha_renovacion'), 'cs_accounts', ['fecha_renovacion'], unique=False)
    op.create_index(op.f('ix_cs_accounts_ticket_token'), 'cs_accounts', ['ticket_token'], unique=True)
    op.create_table('cs_onboarding_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('sucursales', sa.Integer(), nullable=True),
    sa.Column('tarifa', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('frecuencia', sa.String(length=30), nullable=True),
    sa.Column('mrr_proyectado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('kam_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['kam_id'], ['users_crm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_rfcs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('savio_customer_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['customer_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_rfcs_master_id'), 'customer_rfcs', ['master_id'], unique=False)
    op.create_index(op.f('ix_customer_rfcs_rfc'), 'customer_rfcs', ['rfc'], unique=False)
    op.create_index(op.f('ix_customer_rfcs_savio_customer_id'), 'customer_rfcs', ['savio_customer_id'], unique=True)
    op.create_table('metas_vendedor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('mes', sa.Text(), nullable=False),
    sa.Column('meta_mxn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('meta_recurrente_mxn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('meta_eventual_mxn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users_crm.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'mes')
    )
    op.create_table('sales_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendedor_id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.Text(), nullable=False),
    sa.Column('gmail_thread_id', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direccion', sa.String(length=4), server_default='OUT', nullable=False),
    sa.Column('from_email', sa.Text(), nullable=False),
    sa.Column('to_emails', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('cc_emails', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('has_attachment', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    op.create_index(op.f('ix_sales_emails_direccion'), 'sales_emails', ['direccion'], unique=False)
    op.create_index(op.f('ix_sales_emails_gmail_thread_id'), 'sales_emails', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_sales_emails_sent_at'), 'sales_emails', ['sent_at'], unique=False)
    op.create_index(op.f('ix_sales_emails_vendedor_id'), 'sales_emails', ['vendedor_id'], unique=False)
    op.create_table('sdr_dir_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('company_domain', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('contact_title', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.Text(), nullable=True),
    sa.Column('contact_linkedin', sa.Text(), nullable=True),
    sa.Column('whatsapp_verified', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_link', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('first_channel', sa.String(length=40), nullable=False),
    sa.Column('lemlist_campaign_id', sa.Text(), nullable=True),
    sa.Column('lemlist_lead_id', sa.Text(), nullable=True),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lead_state', sa.String(length=60), nullable=False),
    sa.Column('state_reason', sa.Text(), nullable=True),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('master_company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['master_company_id'], ['sdr_dir_master_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdr_dir_sequences_assigned_to'), 'sdr_dir_sequences', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_sdr_dir_sequences_company_name'), 'sdr_dir_sequences', ['company_name'], unique=False)
    op.create_index(op.f('ix_sdr_dir_sequences_contact_email'), 'sdr_dir_sequences', ['contact_email'], unique=False)
    op.create_index(op.f('ix_sdr_dir_sequences_lead_state'), 'sdr_dir_sequences', ['lead_state'], unique=False)
    op.create_index(op.f('ix_sdr_dir_sequences_master_company_id'), 'sdr_dir_sequences', ['master_company_id'], unique=False)
    op.create_index(op.f('ix_sdr_dir_sequences_status'), 'sdr_dir_sequences', ['status'], unique=False)
    op.create_index(op.f('ix_sdr_dir_sequences_unit'), 'sdr_dir_sequences', ['unit'], unique=False)
    op.create_table('state_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'unit', 'user_id', name='uq_state_assignments')
    )
    op.create_index(op.f('ix_state_assignments_state'), 'state_assignments', ['state'], unique=False)
    op.create_index(op.f('ix_state_assignments_unit'), 'state_assignments', ['unit'], unique=False)
    op.create_index(op.f('ix_state_assignments_user_id'), 'state_assignments', ['user_id'], unique=False)
    op.create_table('weekly_kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('calls_made', sa.Integer(), nullable=False),
    sa.Column('whatsapps_sent', sa.Integer(), nullable=False),
    sa.Column('emails_sent', sa.Integer(), nullable=False),
    sa.Column('quotes_sent', sa.Integer(), nullable=False),
    sa.Column('visits_made', sa.Integer(), nullable=False),
    sa.Column('leads_generated', sa.Integer(), nullable=False),
    sa.Column('crm_compliance', sa.Float(), nullable=False),
    sa.Column('target_calls', sa.Integer(), nullable=False),
    sa.Column('target_whatsapps', sa.Integer(), nullable=False),
    sa.Column('target_emails', sa.Integer(), nullable=False),
    sa.Column('target_quotes', sa.Integer(), nullable=False),
    sa.Column('target_visits', sa.Integer(), nullable=False),
    sa.Column('compliance_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_weekly_kpis_user_week')
    )
    op.create_index(op.f('ix_weekly_kpis_user_id'), 'weekly_kpis', ['user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellido', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('puesto', sa.String(length=150), nullable=True),
    sa.Column('departamento', sa.String(length=120), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_account_id'), 'contacts', ['account_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_telefono'), 'contacts', ['telefono'], unique=False)
    op.create_table('cs_appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('propiedad', sa.String(length=300), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('tecnico', sa.String(length=120), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_terminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('titulo_servicio', sa.String(length=200), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('zoho_appointment_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_appointments_zoho_appointment_id'), 'cs_appointments', ['zoho_appointment_id'], unique=False)
    op.create_table('cs_contactos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('puesto', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=200), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cs_dd_surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=48), nullable=False),
    sa.Column('contacto_email', sa.String(length=200), nullable=True),
    sa.Column('enviado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('respondido_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nps', sa.Integer(), nullable=True),
    sa.Column('satisfaccion', sa.Integer(), nullable=True),
    sa.Column('continuidad', sa.String(length=30), nullable=True),
    sa.Column('preocupaciones', sa.Text(), nullable=True),
    sa.Column('areas_mejora', sa.Text(), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=200), nullable=True),
    sa.Column('contacto_puesto', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_dd_surveys_account_id'), 'cs_dd_surveys', ['account_id'], unique=False)
    op.create_index(op.f('ix_cs_dd_surveys_token'), 'cs_dd_surveys', ['token'], unique=True)
    op.create_table('cs_documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_documentos_account_id'), 'cs_documentos', ['account_id'], unique=False)
    op.create_table('cs_encuestas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('nombre_respondente', sa.String(length=200), nullable=True),
    sa.Column('puesto_respondente', sa.String(length=200), nullable=True),
    sa.Column('nps', sa.Integer(), nullable=True),
    sa.Column('csat', sa.Integer(), nullable=True),
    sa.Column('csat_calidad', sa.Integer(), nullable=True),
    sa.Column('csat_respuesta', sa.Integer(), nullable=True),
    sa.Column('csat_comunicacion', sa.Integer(), nullable=True),
    sa.Column('csat_precio', sa.Integer(), nullable=True),
    sa.Column('csat_tecnico', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cs_entregables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('unidad_negocio', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_entrega', sa.String(length=100), nullable=True),
    sa.Column('responsable', sa.String(length=120), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('adjuntos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cs_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('cs_import_key', sa.String(length=80), nullable=True),
    sa.Column('folio', sa.String(length=50), nullable=True),
    sa.Column('serie', sa.String(length=20), nullable=True),
    sa.Column('concepto', sa.String(length=300), nullable=True),
    sa.Column('uen', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('impuestos', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pendiente', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pagado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fecha_cobro', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('estatus', sa.String(length=30), nullable=True),
    sa.Column('savio_invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_invoices_cs_import_key'), 'cs_invoices', ['cs_import_key'], unique=False)
    op.create_index(op.f('ix_cs_invoices_savio_invoice_id'), 'cs_invoices', ['savio_invoice_id'], unique=False)
    op.create_index('ux_cs_invoices_import_key', 'cs_invoices', ['cs_import_key'], unique=True, postgresql_where=sa.text('cs_import_key IS NOT NULL'))
    op.create_index('ux_cs_invoices_savio_invoice_id', 'cs_invoices', ['savio_invoice_id'], unique=True, postgresql_where=sa.text('savio_invoice_id IS NOT NULL'))
    op.create_table('cs_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('adjuntos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cs_objetivos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('metrica', sa.String(length=120), nullable=True),
    sa.Column('valor_objetivo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_actual', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('fecha_objetivo', sa.Date(), nullable=True),
    sa.Column('estatus', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=10), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_inicial', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_objetivos_account_id'), 'cs_objetivos', ['account_id'], unique=False)
    op.create_table('cs_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('prospecto_nombre', sa.String(length=200), nullable=True),
    sa.Column('contacto', sa.String(length=200), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=40), nullable=True),
    sa.Column('contacto_email', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('unidad_negocio', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('etapa', sa.String(length=30), nullable=True),
    sa.Column('kam_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.ForeignKeyConstraint(['kam_id'], ['users_crm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cs_propiedades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('unidad_negocio', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cs_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('responsable', sa.String(length=120), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('adjuntos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cs_workload_surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('kam_id', sa.UUID(), nullable=True),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('horas_cliente', sa.String(length=30), nullable=True),
    sa.Column('carga_esperada', sa.String(length=60), nullable=True),
    sa.Column('motivo_carga', sa.String(length=100), nullable=True),
    sa.Column('actividades_horas', sa.JSON(), nullable=True),
    sa.Column('entregables_count', sa.String(length=60), nullable=True),
    sa.Column('entregables_tipos', sa.JSON(), nullable=True),
    sa.Column('frecuencia_entregable', sa.String(length=60), nullable=True),
    sa.Column('horas_entregables', sa.String(length=30), nullable=True),
    sa.Column('dependencia_externa', sa.String(length=80), nullable=True),
    sa.Column('bloqueos_nivel', sa.String(length=40), nullable=True),
    sa.Column('tipo_bloqueo', sa.String(length=100), nullable=True),
    sa.Column('horas_bloqueos', sa.String(length=30), nullable=True),
    sa.Column('recurrencia_bloqueo', sa.String(length=60), nullable=True),
    sa.Column('reprogramaciones_count', sa.String(length=30), nullable=True),
    sa.Column('incidencias_count', sa.String(length=30), nullable=True),
    sa.Column('horas_incidencias', sa.String(length=30), nullable=True),
    sa.Column('causa_incidencias', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.ForeignKeyConstraint(['kam_id'], ['users_crm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_workload_surveys_account_id'), 'cs_workload_surveys', ['account_id'], unique=False)
    op.create_index(op.f('ix_cs_workload_surveys_kam_id'), 'cs_workload_surveys', ['kam_id'], unique=False)
    op.create_table('kam_email_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kam_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('gmail_thread_id', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('client_email', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_hours', sa.Float(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kam_id'], ['users_crm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kam_id', 'gmail_thread_id', name='uq_kam_email_response')
    )
    op.create_index(op.f('ix_kam_email_responses_account_id'), 'kam_email_responses', ['account_id'], unique=False)
    op.create_index(op.f('ix_kam_email_responses_kam_id'), 'kam_email_responses', ['kam_id'], unique=False)
    op.create_table('sdr_dir_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=40), nullable=True),
    sa.Column('message_preview', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sdr_dir_sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdr_dir_history_sequence_id'), 'sdr_dir_history', ['sequence_id'], unique=False)
    op.create_table('cs_incidencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('propiedad_id', sa.UUID(), nullable=True),
    sa.Column('propiedad_nombre', sa.String(length=300), nullable=True),
    sa.Column('servicio', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('quien_reporta', sa.String(length=200), nullable=True),
    sa.Column('contacto_cliente', sa.String(length=200), nullable=True),
    sa.Column('responsable', sa.String(length=200), nullable=True),
    sa.Column('fecha_incidencia', sa.Date(), nullable=True),
    sa.Column('fecha_compromiso', sa.Date(), nullable=True),
    sa.Column('fecha_solucion', sa.Date(), nullable=True),
    sa.Column('comentarios_operaciones', sa.Text(), nullable=True),
    sa.Column('evidencia', sa.Text(), nullable=True),
    sa.Column('tiempo_respuesta', sa.Integer(), nullable=True),
    sa.Column('cobrable', sa.String(length=20), nullable=True),
    sa.Column('monto_cobro', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('motivo_no_cobro', sa.Text(), nullable=True),
    sa.Column('factura_numero', sa.String(length=60), nullable=True),
    sa.Column('factura_fecha', sa.Date(), nullable=True),
    sa.Column('factura_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cs_accounts.id'], ),
    sa.ForeignKeyConstraint(['propiedad_id'], ['cs_propiedades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_incidencias_folio'), 'cs_incidencias', ['folio'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('origen', sa.Enum('Meta Ads', 'WhatsApp Organico', 'Web', 'Prospeccion', 'Upselling', 'Cross-selling', name='origen_lead_enum'), nullable=True),
    sa.Column('marca_interes', sa.String(length=80), nullable=True),
    sa.Column('marcas_interes', postgresql.ARRAY(sa.String(length=80)), server_default='{}', nullable=False),
    sa.Column('etapa_pipeline', sa.Enum('Nuevo Lead', '1er Contacto', '2do Contacto', '3er Contacto', '4to Contacto', 'Presentación', 'Cotización', 'Demo', 'Negociación', 'Cerrado Ganado', 'Cerrado Perdido', name='etapa_pipeline_enum'), nullable=False),
    sa.Column('cantidad_productos', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('motivo_perdida', sa.Text(), nullable=True),
    sa.Column('tipo_cliente', sa.Text(), nullable=True),
    sa.Column('tipo_venta', sa.String(length=40), nullable=True),
    sa.Column('fecha_ultimo_contacto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proximo_contacto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('en_nurturing', sa.Boolean(), nullable=False),
    sa.Column('respondio_ultimo_contacto', sa.Boolean(), nullable=False),
    sa.Column('icp_score', sa.Integer(), nullable=True),
    sa.Column('icp_nivel', sa.Text(), nullable=True),
    sa.Column('num_sucursales', sa.Integer(), nullable=True),
    sa.Column('tipo_industria', sa.Text(), nullable=True),
    sa.Column('tamano_empresa', sa.Text(), nullable=True),
    sa.Column('estado_cliente', sa.String(length=100), nullable=True),
    sa.Column('empresa_nombre', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('usuario_asignado_id', sa.UUID(), nullable=True),
    sa.Column('factura_numero', sa.String(length=60), nullable=True),
    sa.Column('factura_fecha', sa.Date(), nullable=True),
    sa.Column('factura_monto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('factura_notas', sa.Text(), nullable=True),
    sa.Column('factura_registrada_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_lead_id', sa.String(length=100), nullable=True),
    sa.Column('meta_form_id', sa.String(length=100), nullable=True),
    sa.Column('meta_ad_id', sa.String(length=100), nullable=True),
    sa.Column('meta_campaign', sa.String(length=200), nullable=True),
    sa.Column('shopify_customer_id', sa.String(length=64), nullable=True),
    sa.Column('shopify_checkout_id', sa.String(length=64), nullable=True),
    sa.Column('shopify_order_id', sa.String(length=64), nullable=True),
    sa.Column('bot_step', sa.String(length=30), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo_cliente IS NULL OR tipo_cliente IN ('Recurrente', 'Eventual')", name='leads_tipo_cliente_check'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_asignado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_lead_id')
    )
    op.create_index(op.f('ix_leads_account_id'), 'leads', ['account_id'], unique=False)
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_fecha_cierre'), 'leads', ['fecha_cierre'], unique=False)
    op.create_index(op.f('ix_leads_shopify_checkout_id'), 'leads', ['shopify_checkout_id'], unique=False)
    op.create_index(op.f('ix_leads_shopify_customer_id'), 'leads', ['shopify_customer_id'], unique=False)
    op.create_index(op.f('ix_leads_shopify_order_id'), 'leads', ['shopify_order_id'], unique=False)
    op.create_index(op.f('ix_leads_telefono'), 'leads', ['telefono'], unique=False)
    op.create_table('cotizaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('generado_por', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviada_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=200), nullable=True),
    sa.Column('empresa_cliente', sa.String(length=200), nullable=True),
    sa.Column('direccion_cliente', sa.Text(), nullable=True),
    sa.Column('telefono_cliente', sa.String(length=30), nullable=True),
    sa.Column('correo_cliente', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=80), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('descuento_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('descuento_monto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('condiciones_pago', sa.String(length=100), nullable=True),
    sa.Column('vigencia_dias', sa.Integer(), nullable=True),
    sa.Column('vendedor_nombre', sa.String(length=150), nullable=True),
    sa.Column('enviada_correo', sa.Boolean(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('estado_bot_interno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('lead_contexto_id', sa.UUID(), nullable=True),
    sa.Column('esperando_input', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['lead_contexto_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_atribuciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('etapa', sa.String(length=40), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('es_automatica', sa.Boolean(), nullable=False),
    sa.Column('definida_por', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'etapa', name='uq_lead_etapa')
    )
    op.create_index(op.f('ix_lead_atribuciones_lead_id'), 'lead_atribuciones', ['lead_id'], unique=False)
    op.create_table('mensajes_whatsapp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('direccion', sa.Enum('Entrante', 'Saliente_Vendedor', 'Saliente_Bot', name='direccion_mensaje_enum'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('meta_message_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_message_id')
    )
    op.create_table('oportunidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('empresa', sa.String(length=255), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=150), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=30), nullable=True),
    sa.Column('contacto_email', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=8), nullable=False),
    sa.Column('fecha_cierre_esperada', sa.Date(), nullable=True),
    sa.Column('etapa', sa.Enum('Calificación', 'Análisis', 'Propuesta', 'Negociación', 'Cerrado Ganado', 'Cerrado Perdido', name='etapa_oportunidad_enum'), nullable=False),
    sa.Column('probabilidad', sa.Integer(), nullable=False),
    sa.Column('propietario_id', sa.UUID(), nullable=True),
    sa.Column('marca_interes', sa.String(length=80), nullable=True),
    sa.Column('estado_cliente', sa.String(length=100), nullable=True),
    sa.Column('num_sucursales', sa.Integer(), nullable=True),
    sa.Column('sitio', sa.String(length=200), nullable=True),
    sa.Column('monthly_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sale_type', sa.String(length=40), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('motivo_perdida', sa.Text(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('zoho_deal_id', sa.String(length=80), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_cierre_real', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['propietario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oportunidades_account_id'), 'oportunidades', ['account_id'], unique=False)
    op.create_index(op.f('ix_oportunidades_contact_id'), 'oportunidades', ['contact_id'], unique=False)
    op.create_index(op.f('ix_oportunidades_empresa'), 'oportunidades', ['empresa'], unique=False)
    op.create_index(op.f('ix_oportunidades_etapa'), 'oportunidades', ['etapa'], unique=False)
    op.create_index(op.f('ix_oportunidades_fecha_cierre_esperada'), 'oportunidades', ['fecha_cierre_esperada'], unique=False)
    op.create_index(op.f('ix_oportunidades_lead_id'), 'oportunidades', ['lead_id'], unique=False)
    op.create_index(op.f('ix_oportunidades_marca_interes'), 'oportunidades', ['marca_interes'], unique=False)
    op.create_index(op.f('ix_oportunidades_propietario_id'), 'oportunidades', ['propietario_id'], unique=False)
    op.create_index(op.f('ix_oportunidades_sitio'), 'oportunidades', ['sitio'], unique=False)
    op.create_index(op.f('ix_oportunidades_zoho_deal_id'), 'oportunidades', ['zoho_deal_id'], unique=True)
    op.create_table('cierre_evidencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('oportunidad_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('archivo_url', sa.Text(), nullable=False),
    sa.Column('archivo_nombre', sa.String(length=300), nullable=True),
    sa.Column('subido_por', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo IN ('orden_compra','contrato','correo_confirmacion','whatsapp','cita_operandium')", name='cierre_evidencias_tipo_check'),
    sa.CheckConstraint('(lead_id IS NOT NULL)::int + (oportunidad_id IS NOT NULL)::int = 1', name='cierre_evidencias_un_solo_dueno'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oportunidad_id'], ['oportunidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cierre_evidencias_lead_id'), 'cierre_evidencias', ['lead_id'], unique=False)
    op.create_index(op.f('ix_cierre_evidencias_oportunidad_id'), 'cierre_evidencias', ['oportunidad_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('sale_type', sa.String(length=40), nullable=False),
    sa.Column('sale_category', sa.String(length=40), nullable=False),
    sa.Column('uen', sa.String(length=120), nullable=True),
    sa.Column('lead_source', sa.String(length=120), nullable=True),
    sa.Column('monthly_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contract_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commission_type', sa.String(length=40), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_status', sa.String(length=40), nullable=False),
    sa.Column('commission_pay_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['oportunidades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_lead_id'), 'sales', ['lead_id'], unique=False)
    op.create_index(op.f('ix_sales_opportunity_id'), 'sales', ['opportunity_id'], unique=True)
    op.create_index(op.f('ix_sales_unit'), 'sales', ['unit'], unique=False)
    op.create_index(op.f('ix_sales_user_id'), 'sales', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('service_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=60), nullable=True),
    sa.Column('monthly_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('nps_score', sa.Integer(), nullable=True),
    sa.Column('nps_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_assigned_to'), 'clients', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_clients_rfc'), 'clients', ['rfc'], unique=False)
    op.create_index(op.f('ix_clients_sale_id'), 'clients', ['sale_id'], unique=False)
    op.create_index(op.f('ix_clients_unit'), 'clients', ['unit'], unique=False)
    op.create_table('sale_participaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('etapas', sa.Text(), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_participaciones_sale_id'), 'sale_participaciones', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sale_participaciones_usuario_id'), 'sale_participaciones', ['usuario_id'], unique=False)
    op.create_table('touchpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_touchpoints_client_id'), 'touchpoints', ['client_id'], unique=False)
    op.create_index(op.f('ix_touchpoints_status'), 'touchpoints', ['status'], unique=False)
    op.create_index(op.f('ix_touchpoints_user_id'), 'touchpoints', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Romper el ciclo primero: si no, el drop de cualquiera de las dos falla.
    op.drop_constraint('users_crm_usuario_id_fkey', 'users_crm', type_='foreignkey')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_touchpoints_user_id'), table_name='touchpoints')
    op.drop_index(op.f('ix_touchpoints_status'), table_name='touchpoints')
    op.drop_index(op.f('ix_touchpoints_client_id'), table_name='touchpoints')
    op.drop_table('touchpoints')
    op.drop_index(op.f('ix_sale_participaciones_usuario_id'), table_name='sale_participaciones')
    op.drop_index(op.f('ix_sale_participaciones_sale_id'), table_name='sale_participaciones')
    op.drop_table('sale_participaciones')
    op.drop_index(op.f('ix_clients_unit'), table_name='clients')
    op.drop_index(op.f('ix_clients_sale_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_rfc'), table_name='clients')
    op.drop_index(op.f('ix_clients_assigned_to'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_sales_user_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_unit'), table_name='sales')
    op.drop_index(op.f('ix_sales_opportunity_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_lead_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_cierre_evidencias_oportunidad_id'), table_name='cierre_evidencias')
    op.drop_index(op.f('ix_cierre_evidencias_lead_id'), table_name='cierre_evidencias')
    op.drop_table('cierre_evidencias')
    op.drop_index(op.f('ix_oportunidades_zoho_deal_id'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_sitio'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_propietario_id'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_marca_interes'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_lead_id'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_fecha_cierre_esperada'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_etapa'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_empresa'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_contact_id'), table_name='oportunidades')
    op.drop_index(op.f('ix_oportunidades_account_id'), table_name='oportunidades')
    op.drop_table('oportunidades')
    op.drop_table('mensajes_whatsapp')
    op.drop_index(op.f('ix_lead_atribuciones_lead_id'), table_name='lead_atribuciones')
    op.drop_table('lead_atribuciones')
    op.drop_table('estado_bot_interno')
    op.drop_table('cotizaciones')
    op.drop_index(op.f('ix_leads_telefono'), table_name='leads')
    op.drop_index(op.f('ix_leads_shopify_order_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_shopify_customer_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_shopify_checkout_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_fecha_cierre'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_account_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_cs_incidencias_folio'), table_name='cs_incidencias')
    op.drop_table('cs_incidencias')
    op.drop_index(op.f('ix_sdr_dir_history_sequence_id'), table_name='sdr_dir_history')
    op.drop_table('sdr_dir_history')
    op.drop_index(op.f('ix_kam_email_responses_kam_id'), table_name='kam_email_responses')
    op.drop_index(op.f('ix_kam_email_responses_account_id'), table_name='kam_email_responses')
    op.drop_table('kam_email_responses')
    op.drop_index(op.f('ix_cs_workload_surveys_kam_id'), table_name='cs_workload_surveys')
    op.drop_index(op.f('ix_cs_workload_surveys_account_id'), table_name='cs_workload_surveys')
    op.drop_table('cs_workload_surveys')
    op.drop_table('cs_tasks')
    op.drop_table('cs_propiedades')
    op.drop_table('cs_opportunities')
    op.drop_index(op.f('ix_cs_objetivos_account_id'), table_name='cs_objetivos')
    op.drop_table('cs_objetivos')
    op.drop_table('cs_notes')
    op.drop_index('ux_cs_invoices_savio_invoice_id', table_name='cs_invoices', postgresql_where=sa.text('savio_invoice_id IS NOT NULL'))
    op.drop_index('ux_cs_invoices_import_key', table_name='cs_invoices', postgresql_where=sa.text('cs_import_key IS NOT NULL'))
    op.drop_index(op.f('ix_cs_invoices_savio_invoice_id'), table_name='cs_invoices')
    op.drop_index(op.f('ix_cs_invoices_cs_import_key'), table_name='cs_invoices')
    op.drop_table('cs_invoices')
    op.drop_table('cs_entregables')
    op.drop_table('cs_encuestas')
    op.drop_index(op.f('ix_cs_documentos_account_id'), table_name='cs_documentos')
    op.drop_table('cs_documentos')
    op.drop_index(op.f('ix_cs_dd_surveys_token'), table_name='cs_dd_surveys')
    op.drop_index(op.f('ix_cs_dd_surveys_account_id'), table_name='cs_dd_surveys')
    op.drop_table('cs_dd_surveys')
    op.drop_table('cs_contactos')
    op.drop_index(op.f('ix_cs_appointments_zoho_appointment_id'), table_name='cs_appointments')
    op.drop_table('cs_appointments')
    op.drop_index(op.f('ix_contacts_telefono'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_account_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_weekly_kpis_user_id'), table_name='weekly_kpis')
    op.drop_table('weekly_kpis')
    op.drop_index(op.f('ix_state_assignments_user_id'), table_name='state_assignments')
    op.drop_index(op.f('ix_state_assignments_unit'), table_name='state_assignments')
    op.drop_index(op.f('ix_state_assignments_state'), table_name='state_assignments')
    op.drop_table('state_assignments')
    op.drop_index(op.f('ix_sdr_dir_sequences_unit'), table_name='sdr_dir_sequences')
    op.drop_index(op.f('ix_sdr_dir_sequences_status'), table_name='sdr_dir_sequences')
    op.drop_index(op.f('ix_sdr_dir_sequences_master_company_id'), table_name='sdr_dir_sequences')
    op.drop_index(op.f('ix_sdr_dir_sequences_lead_state'), table_name='sdr_dir_sequences')
    op.drop_index(op.f('ix_sdr_dir_sequences_contact_email'), table_name='sdr_dir_sequences')
    op.drop_index(op.f('ix_sdr_dir_sequences_company_name'), table_name='sdr_dir_sequences')
    op.drop_index(op.f('ix_sdr_dir_sequences_assigned_to'), table_name='sdr_dir_sequences')
    op.drop_table('sdr_dir_sequences')
    op.drop_index(op.f('ix_sales_emails_vendedor_id'), table_name='sales_emails')
    op.drop_index(op.f('ix_sales_emails_sent_at'), table_name='sales_emails')
    op.drop_index(op.f('ix_sales_emails_gmail_thread_id'), table_name='sales_emails')
    op.drop_index(op.f('ix_sales_emails_direccion'), table_name='sales_emails')
    op.drop_table('sales_emails')
    op.drop_table('metas_vendedor')
    op.drop_index(op.f('ix_customer_rfcs_savio_customer_id'), table_name='customer_rfcs')
    op.drop_index(op.f('ix_customer_rfcs_rfc'), table_name='customer_rfcs')
    op.drop_index(op.f('ix_customer_rfcs_master_id'), table_name='customer_rfcs')
    op.drop_table('customer_rfcs')
    op.drop_table('cs_onboarding_accounts')
    op.drop_index(op.f('ix_cs_accounts_ticket_token'), table_name='cs_accounts')
    op.drop_index(op.f('ix_cs_accounts_fecha_renovacion'), table_name='cs_accounts')
    op.drop_index(op.f('ix_cs_accounts_en_due_diligence'), table_name='cs_accounts')
    op.drop_index(op.f('ix_cs_accounts_ejecutivo_id'), table_name='cs_accounts')
    op.drop_table('cs_accounts')
    op.drop_index(op.f('ix_comision_cortes_usuario_id'), table_name='comision_cortes')
    op.drop_index(op.f('ix_comision_cortes_mes'), table_name='comision_cortes')
    op.drop_table('comision_cortes')
    op.drop_index(op.f('ix_city_assignments_user_id'), table_name='city_assignments')
    op.drop_index(op.f('ix_city_assignments_unit'), table_name='city_assignments')
    op.drop_index(op.f('ix_city_assignments_city'), table_name='city_assignments')
    op.drop_table('city_assignments')
    op.drop_index(op.f('ix_chatbot_messages_conversation_id'), table_name='chatbot_messages')
    op.drop_table('chatbot_messages')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_accounts_rfc'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_nombre'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_estado'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_customer_master_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_cs_account_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_client_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('zoho_tokens')
    op.drop_table('usuarios')
    op.drop_table('users_crm')
    op.drop_index(op.f('ix_sdr_results_unit'), table_name='sdr_results')
    op.drop_index(op.f('ix_sdr_results_status'), table_name='sdr_results')
    op.drop_index(op.f('ix_sdr_results_assigned_to'), table_name='sdr_results')
    op.drop_table('sdr_results')
    op.drop_index(op.f('ix_sdr_dir_suggestions_unit'), table_name='sdr_dir_suggestions')
    op.drop_index(op.f('ix_sdr_dir_suggestions_suggested_to'), table_name='sdr_dir_suggestions')
    op.drop_index(op.f('ix_sdr_dir_suggestions_status'), table_name='sdr_dir_suggestions')
    op.drop_table('sdr_dir_suggestions')
    op.drop_index(op.f('ix_sdr_dir_master_companies_unit'), table_name='sdr_dir_master_companies')
    op.drop_index(op.f('ix_sdr_dir_master_companies_status'), table_name='sdr_dir_master_companies')
    op.drop_index('idx_sdr_master_unit_status', table_name='sdr_dir_master_companies')
    op.drop_index('idx_sdr_master_status_priority', table_name='sdr_dir_master_companies')
    op.drop_table('sdr_dir_master_companies')
    op.drop_index(op.f('ix_sdr_dir_engine_runs_unit'), table_name='sdr_dir_engine_runs')
    op.drop_table('sdr_dir_engine_runs')
    op.drop_table('sdr_dir_engine_config')
    op.drop_index('idx_sdr_credits_unit_service_month', table_name='sdr_dir_credits_monthly')
    op.drop_table('sdr_dir_credits_monthly')
    op.drop_index(op.f('ix_scip_director_recommendations_status'), table_name='scip_director_recommendations')
    op.drop_index(op.f('ix_scip_director_recommendations_created_at'), table_name='scip_director_recommendations')
    op.drop_index(op.f('ix_scip_director_recommendations_campaign_id'), table_name='scip_director_recommendations')
    op.drop_table('scip_director_recommendations')
    op.drop_table('savio_sync_state')
    op.drop_index(op.f('ix_savio_subscriptions_unit'), table_name='savio_subscriptions')
    op.drop_index(op.f('ix_savio_subscriptions_customer_id'), table_name='savio_subscriptions')
    op.drop_table('savio_subscriptions')
    op.drop_index(op.f('ix_savio_payments_invoice_id'), table_name='savio_payments')
    op.drop_index(op.f('ix_savio_payments_date'), table_name='savio_payments')
    op.drop_index(op.f('ix_savio_payments_customer_id'), table_name='savio_payments')
    op.drop_table('savio_payments')
    op.drop_index(op.f('ix_savio_invoices_unit'), table_name='savio_invoices')
    op.drop_index(op.f('ix_savio_invoices_date'), table_name='savio_invoices')
    op.drop_index(op.f('ix_savio_invoices_customer_id'), table_name='savio_invoices')
    op.drop_table('savio_invoices')
    op.drop_index(op.f('ix_savio_customers_tax_id'), table_name='savio_customers')
    op.drop_table('savio_customers')
    op.drop_table('proyecto_items')
    op.drop_table('meta_campaigns')
    op.drop_table('gastos_publicidad')
    op.drop_table('customer_master')
    op.drop_index(op.f('ix_comision_tasas_unidad'), table_name='comision_tasas')
    op.drop_table('comision_tasas')
    op.drop_table('comision_politica')
    op.drop_table('comision_etapas')
    op.drop_table('comision_descuentos')
    op.drop_index(op.f('ix_chatbot_conversations_wa_phone'), table_name='chatbot_conversations')
    op.drop_index(op.f('ix_chatbot_conversations_unit'), table_name='chatbot_conversations')
    op.drop_index(op.f('ix_chatbot_conversations_status'), table_name='chatbot_conversations')
    op.drop_table('chatbot_conversations')
    op.drop_index(op.f('ix_chatbot_config_webhook_verify_token'), table_name='chatbot_config')
    op.drop_table('chatbot_config')
    op.drop_index(op.f('ix_api_costs_unit'), table_name='api_costs')
    op.drop_index(op.f('ix_api_costs_service'), table_name='api_costs')
    op.drop_index(op.f('ix_api_costs_created_at'), table_name='api_costs')
    op.drop_index(op.f('ix_api_costs_action'), table_name='api_costs')
    op.drop_table('api_costs')
    op.drop_table('actividad_log')
    # ### end Alembic commands ###
